---
name: Checks # Nombre que aparecer치 en las acciones de github

on: [push] # Este es el trigger que se ejecuta al momento de realizar un push

jobs:
  test-lint:
    name: Test and Lint # Nombre del job
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub # Nombre del paso
        uses: docker/login-action@v1 # Se usar치 una acci칩n prefabricada de github action. Usaremos la de login en docker
        with: # Pasamos las credenciales correspondientes que ya tenemos almacenadas en el secrets de github actions
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout # Este paso verfica el workflow
        uses: actions/checkout@v3
      - name: Test # Este paso ejecuta los tests
        run: docker compose run --rm app sh -c "python manage.py test" # Comando a ejecutar
      - name: Lint # Este paso verifica el c칩digo
        run: docker compose run --rm app sh -c "flake8"

